import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import background from '../public/paintbg.jpg'
import Button from '@material-ui/core/Button'
import Paper from '@material-ui/core/Paper'
import GitHubIcon from '@material-ui/icons/GitHub'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import MailIcon from '@material-ui/icons/Mail'
import ArrowBackIcon from '@material-ui/icons/ArrowBack';
import IconButton from '@material-ui/core/IconButton'
import { AnimatePresence, motion } from 'framer-motion'


export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          ConstanceIngram.dev
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main className={styles.main} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
        <div id="header">
                <IconButton href="/">
                    <ArrowBackIcon id="icon" fontSize="large"></ArrowBackIcon>
                </IconButton>
                <h1 className={styles.title}>
                    About
                </h1>
            </div>
            
        <Paper>
            <div id="aboutsection">
                <p id="about">Constance Ingram is a developer from Austin, TX.</p>
                <p id="about">She graduated from The University of Texas at Austin in 2015 with a Bachelor of Arts in History.</p>
                <p id="about">She currently works as an Intellectual Property Analyst at Accenture @ Facebook.</p>
                <p id="about">You can view her projects and resumes here: </p>
                    <div id="buttons">
                        <Button id="button" href="/projects">Projects</Button>
                        <Button id="button" href="/resume">Resume</Button>
                    </div>
                <p id="about">You can view her GitHub and LinkedIn here: </p>
                    <div id="icons">
                        <IconButton href="https://github.com/ccingram94" target="_blank" rel="noopener noreferrer">
                            <GitHubIcon id="icon2" fontSize="large"></GitHubIcon>
                        </IconButton>
                        <IconButton href="https://www.linkedin.com/in/constance-ingram-7aa067161/" target="_blank" rel="noopener noreferrer">
                            <LinkedInIcon id="icon2" fontSize="large"></LinkedInIcon>
                        </IconButton>
                        <IconButton href="https://github.com/ccingram94" target="_blank" rel="noopener noreferrer">
                            <MailIcon id="icon2" fontSize="large"></MailIcon>
                        </IconButton>
                    </div>
            </div>
        </Paper>
     

      </motion.main>

    </div>
  )
}
