import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import background from '../public/paintbg.jpg'
import Button from '@material-ui/core/Button'
import GitHubIcon from '@material-ui/icons/GitHub'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import MailIcon from '@material-ui/icons/Mail'
import IconButton from '@material-ui/core/IconButton'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>
          ConstanceIngram.dev
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={background} layout="fill" objectFit="cover" alt="groovy paint" id="background"/>
      <div id="overlay"></div>
      <main className={styles.main}>

        <h1 className={styles.title}>
          Constance Ingram
        </h1>
        <h2>Austin, TX</h2>
        <div id="icons">
          <GitHubIcon id="icon" fontSize="large" onClick={event => window.location.href='https://github.com/ccingram94'}></GitHubIcon>
          <LinkedInIcon id="icon" fontSize="large"></LinkedInIcon>
          <MailIcon id="icon" fontSize="large"></MailIcon>
        </div>
        <div id="buttons">
          <Button id="button" href="/about" variant="contained"> About</Button>
          <Button id="button" href="/projects" variant="contained">Projects</Button>
          <Button id="button" href="/resume" variant="contained">Resume</Button>
        </div>

      </main>

    </div>
  )
}
