import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import background from '../public/paintbg.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src={background} layout="fill" objectFit="cover" alt="groovy paint" id="background"/>
      <div id="overlay"></div>
      <main className={styles.main}>

        <h1 className={styles.title}>
          Constance Ingram
        </h1>
        <h2>Austin, TX</h2>

      </main>

    </div>
  )
}
