import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/resume.module.css'
import background from '../public/paintbg.jpg'
import Button from '@material-ui/core/Button'
import Paper from '@material-ui/core/Paper'
import GitHubIcon from '@material-ui/icons/GitHub'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import MailIcon from '@material-ui/icons/Mail'
import IconButton from '@material-ui/core/IconButton'
import ArrowBackIcon from '@material-ui/icons/ArrowBack';
import { motion } from 'framer-motion'
import resumeimg from '../public/resume.jpg'
import { Document, Page  } from 'react-pdf'


export default function Resume() {

  return (
    <div className={styles.container}>
      <Head>
        <title>
          ConstanceIngram.dev
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.main className={styles.main} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
          <div id="header">
            <IconButton href="/">
                <ArrowBackIcon id="icon" fontSize="large"></ArrowBackIcon>
            </IconButton>
            <h1 className={styles.title}>
                Resume
            </h1>
            <div id="pdf">
                <Button variant="contained">PDF</Button>
            </div>
          </div>
            <div id="paperbox">
                <Paper elevation={3} id="paperbox">
                    <Image src={resumeimg} id="resumeimg" alt="my resume, also available in PDF upon request" width={700} height={950}></Image>
                </Paper>
            </div>
      </motion.main>

    </div>
  )
  
}
